### ISSUE TITLE
[LD] Login

### ISSUE THREAD

**Issue by aydenden** [JAVACAFE-STUDY/chainity-landing#4]
- 로그인 페이지 구성

**Comment by rygh4775** [comment]
@yoonhona 로그인에 따른 헤더 버튼 목록도 같이 작업 부탁드려요.
## 헤더 버튼 목록 
### 로그인 전 랜딩 페이지 
1. 로그인
2. 가입
### 로그인 후 랜딩 페이지
1. 나의 페이지
2. 로그아웃
### 로그인 페이지
1. 가입
### 마이 페이지
1. 로그아웃

**Comment by aydenden** [comment]
로컬 개발 시 package.json 파일 설정 추가 필요
"proxy": "자바카페 api 도메인"
